-- [[ INDRA HUB - POTATO (MINIFIED/SAFE MODE) ]] --
-- Copy SEMUA kode dibawah ini ke Pastebin:

if getgenv then getgenv().IndraHubRunning = false; task.wait(0.5); getgenv().IndraHubRunning = true end
local P = game:GetService("Players"); local RS = game:GetService("ReplicatedStorage"); local RUN = game:GetService("RunService"); local VIM = game:GetService("VirtualInputManager"); local UIS = game:GetService("UserInputService"); local CG = game:GetService("CoreGui"); local LP = P.LocalPlayer
local CFG = {RollDelay = 0.5, TickRate = 10, CollectSpeed = 0.2, UIUpdateRate = 5.0}
local DiceDB = {["Basic Dice"]={Cost=300, Luck=1}, ["Silver Dice"]={Cost=2500, Luck=1.5}, ["Golden Dice"]={Cost=20000, Luck=2.5}, ["Aureline Dice"]={Cost=75000, Luck=5}, ["Crystallum Dice"]={Cost=250000, Luck=10}, ["Diamond Dice"]={Cost=2000000, Luck=15}, ["Nebulite Dice"]={Cost=5000000, Luck=20}, ["Galaxion Dice"]={Cost=15000000, Luck=31}, ["Quantum Dice"]={Cost=20000000, Luck=36}, ["Devil Dice"]={Cost=30000000, Luck=51}, ["Heaven Dice"]={Cost=50000000, Luck=61}, ["Nebula Dice"]={Cost=100000000, Luck=81}, ["Singularity Dice"]={Cost=250000000, Luck=150}, ["Aqua Dice"]={Cost=500000000, Luck=250}, ["Lucky Dice"]={Cost=1000000000, Luck=350}, ["Void Dice"]={Cost=1800000000, Luck=500}, ["Ethereal Dice"]={Cost=2000000000, Luck=750}, ["Celestial Dice"]={Cost=10000000000, Luck=920}, ["Solar Dice"]={Cost=50000000000, Luck=1150}, ["Abyssal Dice"]={Cost=100000000000, Luck=1350}, ["Hell Dice"]={Cost=500000000000, Luck=1500}, ["Infinity Dice"]={Cost=1000000000000, Luck=1750}, ["Blackhole Dice"]={Cost=5000000000000, Luck=2050}, ["Death Dice"]={Cost=10000000000000, Luck=2400}, ["Paradoxical Dice"]={Cost=50000000000000, Luck=2800}, ["Soul Dice"]={Cost=100000000000000, Luck=3250}, ["Joker Dice"]={Cost=500000000000000, Luck=3900}, ["Reality Dice"]={Cost=1000000000000000, Luck=4650}, ["Kraken Dice"]={Cost=2000000000000000, Luck=6000}, ["Seraphic Dice"]={Cost=4000000000000000, Luck=8000}, ["Galactic Dice"]={Cost=6000000000000000, Luck=10000}, ["Eldritch Dice"]={Cost=8000000000000000, Luck=12500}, ["Emperor Dice"]={Cost=10000000000000000, Luck=15000}}
local DNames = {}; for k,v in pairs(DiceDB) do table.insert(DNames, k) end; table.sort(DNames, function(a,b) return (DiceDB[a].Cost or 0) < (DiceDB[b].Cost or 0) end)
local Eggs = {"CatEgg", "DogEgg", "CubeEgg", "SlimeEgg", "NullEgg", "AquaEgg", "MartianEgg", "BackroomsEgg"}; local Potions = {"Luck Potion 1","Luck Potion 2","Luck Potion 3","Money Potion 1","Money Potion 2","Money Potion 3","Mutation Chance Potion 1"}; local Rarities = {"Common","Rare","Epic","Legendary","Mythic","Divine","Prismatic","Sacred","Secret","Godly","Cosmic","Apex"}
local function PNum(v) if not v then return 0 end; if type(v) == "number" then return v end; local c = string.gsub(v, "[,%s]", ""); local n = tonumber(string.match(c, "[%d%.]+") or "0") or 0; local s = string.match(c, "[%a]+"); local M = {k=1e3, M=1e6, B=1e9, T=1e12, Qd=1e15, Qn=1e18, Sx=1e21, Sp=1e24, Oc=1e27, N=1e30, Dc=1e33}; if s and M[s] then return n * M[s] end; return n end
local function SInv(rn, ...) local r = RS.Events:FindFirstChild(rn); if not r then return end; local a = {...}; pcall(function() if r:IsA("RemoteFunction") then r:InvokeServer(unpack(a)) elseif r:IsA("RemoteEvent") then r:FireServer(unpack(a)) end end) end
local CacheCol = {}; local function Track(o) if o.Name == "Collect" and o:FindFirstChild("Touch") then table.insert(CacheCol, o.Touch) end end; for _, v in pairs(workspace:GetDescendants()) do Track(v) end; workspace.DescendantAdded:Connect(Track)
local CacheBtn = {}; local function Click(nm) local k = nm:lower(); if CacheBtn[k] and CacheBtn[k].Parent and CacheBtn[k].Visible then local b = CacheBtn[k]; local p = b.AbsolutePosition; local s = b.AbsoluteSize; local c = p + (s / 2); VIM:SendMouseButtonEvent(c.X, c.Y, 0, true, game, 1); task.wait(); VIM:SendMouseButtonEvent(c.X, c.Y, 0, false, game, 1); return true end; local pg = LP:FindFirstChild("PlayerGui"); if not pg then return false end; for _, v in pairs(pg:GetDescendants()) do if v:IsA("GuiButton") and v.Visible then if string.find(v.Name:lower(), k) or (v:FindFirstChild("TextLabel") and string.find(v.TextLabel.Text:lower(), k)) then CacheBtn[k] = v; return Click(nm) end end end; return false end
local function GStats() local ls = LP:FindFirstChild("leaderstats"); return ls and PNum(ls:FindFirstChild("Coins") and ls.Coins.Value) or 0, 0, 0 end
local function GEvent() local s = RS:FindFirstChild("status"); if not s then return "Normal", 0 end; local e = s:GetAttribute("event"); if not e or e == "" then return "Normal", 0 end; return e, math.max(0, (s:GetAttribute("event_end_time") or 0) - os.time()) end
local function BestDice() local bd, bl = nil, -1; local inv = LP.PlayerGui:FindFirstChild("Main") and LP.PlayerGui.Main:FindFirstChild("Dice") and LP.PlayerGui.Main.Dice:FindFirstChild("List"); if inv then for _, v in pairs(inv:GetChildren()) do if DiceDB[v.Name] and DiceDB[v.Name].Luck > bl then bl = DiceDB[v.Name].Luck; bd = v.Name end end end; return bd or Options.NormalDice.Value end
local function GLeg(c) return c:FindFirstChild("RightFoot") or c:FindFirstChild("Right Leg") or c:FindFirstChild("HumanoidRootPart") end
local function Abb(n) local s = {"k","M","B","T","Qd","Qn","Sx"}; for i=#s, 1, -1 do local v = 10^(i*3); if n >= v then return string.format("%.1f", n/v)..s[i] end end; return tostring(n) end
local function ClearLag() pcall(function() if workspace:FindFirstChild("Effects") then workspace.Effects:ClearAllChildren() end; for _,v in pairs(workspace:GetDescendants()) do if v:IsA("Texture") or v:IsA("Decal") or v:IsA("ParticleEmitter") or v:IsA("Trail") then v:Destroy() end end end) end
game:GetService("Lighting").GlobalShadows = false; settings().Rendering.QualityLevel = "Level01"; ClearLag()
local Lib = loadstring(game:HttpGet('https://raw.githubusercontent.com/violin-suzutsuki/LinoriaLib/main/Library.lua'))(); local Win = Lib:CreateWindow({Title = 'Indra Hub | SAFE MODE', Center = true, AutoShow = true}); local Tabs = {M = Win:AddTab('Main'), S = Win:AddTab('Shop'), X = Win:AddTab('Misc'), Z = Win:AddTab('Settings')}
local G1 = Tabs.M:AddLeftGroupbox('Farming'); G1:AddToggle('AR', { Text = 'Auto Roll (0.5s)', Default = false }); G1:AddToggle('AC', { Text = 'Auto Collect', Default = false }); G1:AddToggle('APB', { Text = 'Auto Place Best', Default = false })
local G2 = Tabs.M:AddLeftGroupbox('Stats'); local L1 = G2:AddLabel('Wait...'); local L2 = G2:AddLabel('Wait...')
local G3 = Tabs.M:AddRightGroupbox('Spin/Event'); G3:AddToggle('AS', { Text = 'Auto Spin', Default = false }); local L3 = G3:AddLabel('Spin: Wait...'); G3:AddToggle('AES', { Text = 'Event Sniper', Default = false }); G3:AddDropdown('ND', { Values = DNames, Default = 1, Text = 'Normal' }); G3:AddDropdown('ED', { Values = DNames, Default = 1, Text = 'Sniper' }); G3:AddDropdown('TE', { Values = {"Rain", "Blizzard", "Golden Hour", "Candy Crush", "Slime Rain", "Solar Flare", "Aurora Borealis"}, Default = {}, Multi = true, Text = 'Events' })
local G4 = Tabs.M:AddRightGroupbox('Manage'); G4:AddToggle('ASE', { Text = 'Auto Sell', Default = false }); G4:AddDropdown('SF', { Values = Rarities, Default = {}, Multi = true, Text = 'Sell List' }); G4:AddToggle('ARB', { Text = 'Auto Rebirth', Default = false }); G4:AddToggle('ARS', { Text = 'Auto Restock', Default = false }); G4:AddToggle('ACT', { Text = 'Claim Gifts', Default = false }); G4:AddToggle('ACQ', { Text = 'Claim Quests', Default = false })
local G5 = Tabs.S:AddLeftGroupbox('Shop'); G5:AddToggle('BD', { Text = 'Buy Dice', Default = false }); G5:AddDropdown('SD', { Values = DNames, Default = {}, Multi = true, Text = 'Dice List' }); G5:AddToggle('BP', { Text = 'Buy Potion', Default = false }); G5:AddDropdown('SP', { Values = Potions, Default = {}, Multi = true, Text = 'Pot List' }); G5:AddToggle('UP', { Text = 'Use Potion', Default = false }); G5:AddToggle('BE', { Text = 'Hatch Egg', Default = false }); G5:AddDropdown('SE', { Values = Eggs, Default = 1, Text = 'Egg' }); G5:AddInput('CA', { Default = '1', Numeric = true, Text = 'Amount' })
local G6 = Tabs.X:AddLeftGroupbox('Opt'); G6:AddButton('Boost FPS', function() ClearLag() end); G6:AddToggle('BS', { Text = 'Black Screen', Default = false, Callback = function(v) RUN:Set3dRenderingEnabled(not v) end }); G6:AddToggle('AFK', { Text = 'Anti-AFK', Default = false }); G6:AddButton('No Cutscene', function() for i=1, #Rarities do SInv("updateSettings", "Cutscenes", Rarities[i]) end end)
local G7 = Tabs.Z:AddLeftGroupbox('Menu'); G7:AddButton('Unload', function() if getgenv then getgenv().IndraHubRunning=false end; Lib:Unload(); if game.CoreGui:FindFirstChild("IndraHubToggle") then game.CoreGui.IndraHubToggle:Destroy() end; RUN:Set3dRenderingEnabled(true) end); Lib.ToggleKeybind = Options.MenuKeybind
local FC = 0; local LUI = 0; local LC = 0; local LR = 0; local SS = {T = 0}
RUN.Heartbeat:Connect(function()
    if getgenv and not getgenv().IndraHubRunning then return end; FC = FC + 1; if FC % CFG.TickRate ~= 0 then return end; local clk = os.clock()
    if Toggles.AR.Value and (clk - LR > CFG.RollDelay) then SInv("RollState"); SInv("Roll"); ClearLag(); local m = LP.PlayerGui:FindFirstChild("Main"); if m and m:FindFirstChild("Dice") and m.Dice:FindFirstChild("RollState") then m.Dice.RollState:InvokeServer() end; Click("Roll"); LR = clk end
    if clk - LUI > CFG.UIUpdateRate then local m, g = GStats(); L1:SetText(string.format("C: %s | G: %s", Abb(m), Abb(g))); local en, el = GEvent(); L2:SetText(el > 0 and string.format("E: %s", en) or "E: None"); if FC % 500 == 0 then CacheCol = {} end; LUI = clk end
    if Toggles.AC.Value and clk - LC > CFG.CollectSpeed then if #CacheCol > 0 and LP.Character then local t = CacheCol[1]; local l = GLeg(LP.Character); local r = LP.Character:FindFirstChild("HumanoidRootPart"); if t and t.Parent and l and r then if (t.Position - r.Position).Magnitude <= 150 then firetouchinterest(l, t, 0); firetouchinterest(l, t, 1); local v = r.AssemblyLinearVelocity; r.AssemblyLinearVelocity = Vector3.new(v.X, 0, v.Z); table.remove(CacheCol, 1) else table.remove(CacheCol, 1) end else table.remove(CacheCol, 1) end end; LC = clk end
    if Toggles.AS.Value then if os.time() >= SS.T then local b = BestDice(); local o = Options.ND.Value; if b then SInv("equip", b) end; SInv("spinrequest"); Click("Spin"); for _, v in pairs(workspace:GetDescendants()) do if v:IsA("ProximityPrompt") and string.find(v.ActionText:lower(), "spin") then fireproximityprompt(v) end end; task.delay(0.5, function() SInv("equip", o) end); SS.T = os.time() + 30 end end
    if FC % 40 == 0 then if Toggles.AES.Value then local en, _ = GEvent(); local tg = Options.ND.Value; for k, v in pairs(Options.TE.Value) do if v and en == k then tg = Options.ED.Value; break end end; SInv("equip", tg) end; if Toggles.ASE.Value then SInv("sell", "all") end; if Toggles.ARB.Value then SInv("rebirth") end; if Toggles.ARS.Value then SInv("restock") end; if Toggles.ACT.Value then SInv("ClaimTimeReward"); SInv("claimAll"); SInv("DontLeave") end; if Toggles.ACQ.Value then SInv("QuestRemote", "ClaimReward", "All") end; local amt = tonumber(Options.CA.Value) or 1; if amt < 1 then amt = 1 end; if Toggles.BD.Value then for n, a in pairs(Options.SD.Value) do if a then SInv("buy", n, amt, "dice") end end end; if Toggles.BP.Value then for n, a in pairs(Options.SP.Value) do if a then SInv("buy", n, amt, "potion") end end end; if Toggles.BE.Value then SInv("RegularPet", Options.SE.Value, 1) end end
end)
task.spawn(function() while getgenv and getgenv().IndraHubRunning do if Toggles.APB.Value then SInv("PlaceBestBaddies"); Click("Place Best") end; task.wait(5) end end)
LP.Idled:Connect(function() if Toggles.AFK.Value and getgenv and getgenv().IndraHubRunning then VIM:SendKeyEvent(true, Enum.KeyCode.RightControl, false, game); task.wait(0.1); VIM:SendKeyEvent(false, Enum.KeyCode.RightControl, false, game) end end)
print("Indra Hub SAFE MODE Loaded!")